// <auto-generated />
// This file documents the diagnostic ID conventions used by KeenEyes analyzers.
// Actual diagnostics are defined in their respective analyzer files.

namespace KeenEyes.Generators;

/// <summary>
/// Documentation of diagnostic ID ranges used by KeenEyes analyzers.
/// </summary>
/// <remarks>
/// <para>
/// All KeenEyes diagnostics use the prefix "KEEN" followed by a 3-digit number.
/// The ID ranges are organized by feature area:
/// </para>
/// <list type="table">
/// <listheader>
/// <term>Range</term>
/// <description>Feature Area</description>
/// </listheader>
/// <item>
/// <term>KEEN001-KEEN009</term>
/// <description>System ordering and execution (SystemOrderingAnalyzer, PluginExtensionGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN010-KEEN019</term>
/// <description>Component validation constraints (ComponentValidationAnalyzer)</description>
/// </item>
/// <item>
/// <term>KEEN020-KEEN025</term>
/// <description>Bundle validation (BundleGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN026-KEEN029</term>
/// <description>Mixin validation (MixinGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN030-KEEN039</term>
/// <description>Performance analyzers (RandomClassAnalyzer, LinqHotPathAnalyzer)</description>
/// </item>
/// <item>
/// <term>KEEN040-KEEN049</term>
/// <description>Numeric precision (FloatEqualityAnalyzer)</description>
/// </item>
/// <item>
/// <term>KEEN050-KEEN059</term>
/// <description>Query validation (IWorldCastAnalyzer, QueryGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN060-KEEN069</term>
/// <description>Scene file validation (SceneGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN070-KEEN079</term>
/// <description>Prefab file validation (PrefabGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN080-KEEN089</term>
/// <description>World configuration validation (WorldConfigGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN090-KEEN099</term>
/// <description>Editor extension validation (EditorExtensionGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN100-KEEN109</term>
/// <description>Replication/networking (ReplicatedGenerator)</description>
/// </item>
/// <item>
/// <term>KEEN110-KEEN119</term>
/// <description>Component migration validation (ComponentMigrationAnalyzer)</description>
/// </item>
/// <item>
/// <term>KEEN120-KEEN129</term>
/// <description>Asset path validation (AssetPathAnalyzer)</description>
/// </item>
/// </list>
/// <para>
/// When adding new diagnostics:
/// </para>
/// <list type="number">
/// <item>Use the appropriate range for the feature area</item>
/// <item>Use the next available number within that range</item>
/// <item>Add XML documentation with the format "KEEN###: Description"</item>
/// <item>Keep related diagnostics numerically adjacent</item>
/// </list>
/// </remarks>
internal static class DiagnosticIds
{
    // This file is intentionally empty except for documentation.
    // Diagnostics are defined in their respective analyzer files.
}
