using System.Text.Json;

namespace KeenEyes.Serialization;

/// <summary>
/// Extended migrator interface that provides diagnostic capabilities for migration operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface extends <see cref="IComponentMigrator"/> with methods for:
/// <list type="bullet">
/// <item><description>Migrating with detailed timing and step information</description></item>
/// <item><description>Inspecting migration graphs for components</description></item>
/// <item><description>Finding migration chain gaps</description></item>
/// <item><description>Generating diagnostic reports</description></item>
/// </list>
/// </para>
/// <para>
/// Implementations are generated by the source generator when components define
/// migration methods using <c>[MigrateFrom]</c>.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var diagnostics = serializer as IMigrationDiagnostics;
/// if (diagnostics is not null)
/// {
///     // Get detailed migration result with timing
///     var result = diagnostics.MigrateWithDiagnostics("MyComponent", data, 1, 4);
///     Console.WriteLine(result.TotalElapsed);
///
///     // Inspect the migration graph
///     var graph = diagnostics.GetMigrationGraph(typeof(MyComponent));
///     Console.WriteLine(graph.ToDiagnosticString());
/// }
/// </code>
/// </example>
public interface IMigrationDiagnostics : IComponentMigrator
{
    /// <summary>
    /// Migrates component data with detailed diagnostic information.
    /// </summary>
    /// <param name="typeName">The fully-qualified type name of the component.</param>
    /// <param name="data">The JSON element containing the component data.</param>
    /// <param name="fromVersion">The source version of the component data.</param>
    /// <param name="toVersion">The target version to migrate to.</param>
    /// <returns>
    /// A <see cref="MigrationResult"/> containing the migrated data and timing information.
    /// </returns>
    /// <remarks>
    /// <para>
    /// Unlike <see cref="IComponentMigrator.Migrate(string, JsonElement, int, int)"/>,
    /// this method captures detailed timing for each migration step and returns
    /// a rich result object with diagnostic information.
    /// </para>
    /// <para>
    /// Use this method when you need to:
    /// <list type="bullet">
    /// <item><description>Profile migration performance</description></item>
    /// <item><description>Debug slow migrations</description></item>
    /// <item><description>Get detailed error information on failure</description></item>
    /// </list>
    /// </para>
    /// </remarks>
    MigrationResult MigrateWithDiagnostics(
        string typeName,
        JsonElement data,
        int fromVersion,
        int toVersion);

    /// <summary>
    /// Migrates component data with detailed diagnostic information.
    /// </summary>
    /// <param name="type">The component type.</param>
    /// <param name="data">The JSON element containing the component data.</param>
    /// <param name="fromVersion">The source version of the component data.</param>
    /// <param name="toVersion">The target version to migrate to.</param>
    /// <returns>
    /// A <see cref="MigrationResult"/> containing the migrated data and timing information.
    /// </returns>
    MigrationResult MigrateWithDiagnostics(
        Type type,
        JsonElement data,
        int fromVersion,
        int toVersion);

    /// <summary>
    /// Gets the migration graph for a component type.
    /// </summary>
    /// <param name="typeName">The fully-qualified type name of the component.</param>
    /// <returns>
    /// The migration graph for the component, or <c>null</c> if the component
    /// has no migrations defined.
    /// </returns>
    /// <remarks>
    /// The returned graph can be used to:
    /// <list type="bullet">
    /// <item><description>Inspect available migration paths</description></item>
    /// <item><description>Find gaps in the migration chain</description></item>
    /// <item><description>Generate diagnostic reports</description></item>
    /// </list>
    /// </remarks>
    MigrationGraph? GetMigrationGraph(string typeName);

    /// <summary>
    /// Gets the migration graph for a component type.
    /// </summary>
    /// <param name="type">The component type.</param>
    /// <returns>
    /// The migration graph for the component, or <c>null</c> if the component
    /// has no migrations defined.
    /// </returns>
    MigrationGraph? GetMigrationGraph(Type type);

    /// <summary>
    /// Gets all component types that have migrations defined.
    /// </summary>
    /// <returns>An enumerable of type names with migrations.</returns>
    IEnumerable<string> GetComponentsWithMigrations();

    /// <summary>
    /// Finds all gaps in migration chains across all registered components.
    /// </summary>
    /// <returns>
    /// A dictionary mapping component type names to their missing version migrations.
    /// Only includes components that have at least one gap.
    /// </returns>
    /// <remarks>
    /// <para>
    /// A gap exists when a component at version N is missing a migration from some
    /// version V to V+1 (where 1 ≤ V &lt; N).
    /// </para>
    /// <para>
    /// Use this method to identify incomplete migration chains that would prevent
    /// loading older save files.
    /// </para>
    /// </remarks>
    IReadOnlyDictionary<string, IReadOnlyList<int>> FindAllMigrationGaps();

    /// <summary>
    /// Generates a complete diagnostic report for all migrations.
    /// </summary>
    /// <returns>A multi-line string containing diagnostic information.</returns>
    /// <remarks>
    /// The report includes:
    /// <list type="bullet">
    /// <item><description>All registered components with migrations</description></item>
    /// <item><description>Migration graphs for each component</description></item>
    /// <item><description>Any gaps or issues detected</description></item>
    /// </list>
    /// </remarks>
    string GenerateDiagnosticReport();
}
